name = "todoapp"
main = "worker.js"
compatibility_date = "2025-10-06"

[[d1_databases]]
binding = "TODO_DB"
database_name = "todo-db"
database_id = "a0287dee-980c-44d0-8f84-721c863962cf"
# database_id will be provided by Cloudflare Pages binding
